name: the sense
favicon: null
layout_spectrum: 0.8569952442776412
typography_spectrum: 0.8854070641100407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11486732284538448
  lightness: 0.04148742533288896
  saturation: 0.7968072614166886
  rhythmicContrast: 0.29207539767958224
purpose: []
